### ISSUE TITLE
 Undeclared identifier: 'pidAllPlatforms'

### ISSUE THREAD

**Issue by limelect** [havrlisan/zx-skiacomponents#1]
D10.2.3
unit Zx.SvgBrushList;  line 74

[dcc32 Error] Zx.SvgBrushList.pas(74): E2003 Undeclared identifier: 'pidAllPlatforms'

**Comment by havrlisan** [comment]
I've replaced the _pidAllPlatforms_ with _SkSupportedPlatformsMask_ from the _FMX.Skia_ unit. Another thing I realized is that before D12, unit names from Skia were different (eg. _FMX.Skia_ was _Skia.FMX_), so I wrapped that in compiler directives.

**Commit**: _a01ea3d - pidAllPlatforms -> SkSupportedPlatformsMask, support pre-D12 s4d_
