### ISSUE TITLE
A new issue

### ISSUE THREAD

**Issue by limelect** [havrlisan/zx-skiacomponents#2]
Same problem on both bpl
![Screenshot - 10_04_2024 , 10_45_14](https://github.com/havrlisan/zx-skiacomponents/assets/4199131/ad6f52b2-97e6-426f-8f05-23de27aded4c)
 I cleaned the directory since your files made a lot of problems
some thing with the dpk makes on bothe bpl compiling problems

Checking project dependencies...
Compiling Zx.SkiaComponents.Design.dproj (Debug, Win32)
The imported project file could not be loaded. 'Edition' is an unexpected token. The expected token is '='. Line 58, position 28.  C:\Users\LimElect\AppData\Roaming\Embarcadero\BDS\19.0\environment.proj
[Fatal Error] The imported project file cou
ld not be loaded. 'Edition' is an unexpected token. The expected token is '='. Line 58, position 28.  C:\Users\LimElect\AppData\Roaming\Embarcadero\BDS\19.0\environment.proj

**Comment by limelect** [comment]
No matter what I do i get the same error
I cannot find token is '='. Line 58, position 28.

**Comment by havrlisan** [comment]
I see you're using Delphi 10.2 Tokyo, and these packages are made in Delphi 12 Athens. I've separated the package into an additional folder _RAD Studio 12 Athens_ so it is clear which Delphi version the packages are for. Unfortunately, I currently only have the RAD Studio 12 Athens version installed on my machine, so I'm not able to create packages for earlier versions. If you have the time, feel free to create them yourself and make a pull request, I'll gladly add them!

**Commit:** f19d570 - _Separate packages per Delphi versions_

**Comment by limelect** [comment]
I will make my own 
P.S if you want us to use your work D12 is not the only one.
otherwise it is a toy !

Tried to make my own it is unusable
Good luck

**Comment by havrlisan** [comment]
> Tried to make my own it is unusable

What is _unusable_? What do you mean by "tried to make my own"? I cannot help you if you're not willing to describe your issue.
