### ISSUE TITLE
Error in new skia 6.2

### ISSUE THREAD

**Issue by abritolda** [havrlisan/zx-skiacomponents#5]
After install Skia 6.2 in delphi 12.1 when use a  TZxButton gives this error.

![image](https://github.com/havrlisan/zx-skiacomponents/assets/5874430/db39f833-f776-4b89-81bc-3b7f2824224b)

**Comment by havrlisan** [comment]
Here's a transcript from [skia4delphi](https://t.me/skia4delphi)'s Telegram chat:

> Vinicius Felipe, [17.06.2024. 1:02]
> The workaround is: 
> 1. Create a new unit, like "FullDemo.Startup.pas", and move the "GlobalUseSkia := True;" to this new unit, on initialization section;
> 2. Add this new unit to your dpr uses, but it must be before any of yours unit (like immediately after FMX.Forms);

> Alberto Brito 🇵🇹, [17.06.2024. 12:21]
> with Vinicius's solution it works, but that option don't make much sence

> Alberto Brito 🇵🇹, [17.06.2024. 12:27]
> What changed in skia from version 6.1 to 6.2 that made it necessary to use this initialisation unit with the zx-components

> Vinicius Felipe, [17.06.2024. 14:43]
> The behavior is exactly the same of old versions, so probably your “GlobalUseSkia := True;” was not taking effect in your old project. Remember that this is just to replace the FMX render by skia render, so without this skia will already work (skia controls, api, codecs, ..) but not the render (form and bitmap render)

I've also implemented this workaround in the FullDemo project.
